name: Publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/dev/HESIMS/HESIMS.sln

    - name: Build
      run: dotnet build ./src/dev/HESIMS/HESIMS.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./src/dev/HESIMS/HESIMS.sln --configuration Release --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish ./src/dev/HESIMS/HESIMS.Web/HESIMS.Web.csproj --configuration Release --no-build --no-restore --output ./src/dev/HESIMS/HESIMS.Web/bin/Release/net7.0/publish
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: HESIMS
        path: ./src/dev/HESIMS/HESIMS.Web/bin/Release/net7.0/publish
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./src/dev/HESIMS/HESIMS.Web/bin/Release/net7.0/publish
        asset_name: HESIMS
        asset_content_type: application/zip
